routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return 'Herzlich Willkommen und ab an die <a href="/todo">Arbeit!</a>';
});
//Todo (Aufgaben/ Projekte)
Route::resource('/todo','TodoController');
//TodoItem (Unteraufgaben)
Route::post('/todoitem','TodoItemController@store')->name('todoitem.store');
Route::get('/todoitem/{todoitem}/edit','TodoItemController@edit')->name('todoitem.edit');
Route::put('/todoitem/{todoitem}','TodoItemController@update')->name('todoitem.update');
Route::delete('/todoitem/{todoitem}','TodoItemController@destroy')->name('todoitem.destroy');

app/Models/Todo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Todo extends Model
{
    use HasFactory;

    protected $fillable= [
        'name'
    ];
    
    // Todo:Todoitems == 1:n
    public function todoitems(){
        return $this->hasMany(TodoItem::class,'todo_id','id');
    }
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Todo;
use App\Models\TodoItem;
use Illuminate\Http\Request;

class TodoController extends Controller
{
    public $rules=[
        'name' => 'required|min:3|unique:todos,name'
    ]; // Todo- Titel
    
    /**
     * Alle Todos bzw. Projekte anzeigen.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // SQL SELECT * FROM todos ORDER BY (created_at oder name)
        //$todos= Todo::select()->orderBy('created_at','desc')->withCount('todoitems')->get(); // Todoitems in Abfrage einbinden! (PK)
        $todos= Todo::with('todoitems')->select()->orderBy('created_at','desc')->withCount('todoitems')->get();
        
        return view('todo.index',compact('todos'));
    }

    /**
     * Zeige Formular zum Erstellen neuer Todos.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('todo.create'); //oder todo.edit wenn ein Formular für beides
    }

    /**
     * Neues Todo speichern.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // 1. Validation
        $request->validate($this->rules); //rules s oben
        $todo=[ 'name' => $request->name];
        Todo::create($todo);

        return redirect()->route('todo.index')->with('success','Neues Todo- Item '.$request->name.' erstellt!');
    }

    /**
     * Einzelnes Todo anzeigen.
     *
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function show(Todo $todo)
    {
        $todoitems= TodoItem::where('todo_id',$todo->id)->get(); //Eloquent- collection
        //dd(compact('todoitems'),$todoitems, $todo);
        return view('todo.show', compact('todo','todoitems'));
    }

    /**
     * Formular zeigen zum bearbeiten eines spezifischen Todos.
     *
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function edit(Todo $todo)
    {
        return view('todo.edit',compact('todo'));
    }

    /**
     * Todo ändern
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Todo  $todo
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Todo $todo)
    {
        $request->validate($this->rules);

        $todo->update([ 'name' => $request->name ]);

        return redirect()->route('todo.index')->with('success','Aufgabe '.$request->name .' geändert.');
    }

    /**
     * Spezifisches Todo löschen.
     *
     * @param  \App\Models\Todo $todo
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        //$todo=Todo::select($id)->withCount('todoitems'); //liefert Eloquent Builder"
        //$todo=Todo::find($id)->withCount('todoitems'); //Builder
        $todo=Todo::withCount('todoitems')->find($id);
        //dd($todo, $todo->todoitem_count);
        
        //Löschen soll nur möglich sein wenn keine Unteraufgaben vorhanden sind
        if ($todo && $todo->todoitems_count < 1){
            Todo::destroy($id);
            $status=200;
            $key='success';
            $msg= $todo->name.' erledigt!';
        }
        else if ($todo){
            $status=470;
            $key='warning';
            $msg='Die Aufgabe darf noch nicht gelöscht werden!';
        }
        else {
            $status=480;
            $key='error';
            $msg='Aufgabe nicht gefunden';
        }
        
        if ( request()-> ajax() ){
            return response()->json(['status'=>$status,'key'=>$key ,'msg'=>$msg]);
        }
        
        return redirect()->route('todo.index')->with($key,$msg);
    }
}

resources/views/todo/create.blade.php
@extends('layouts.main')
@section('pageTitle')

@section('content')

    <h1>Neue Todo Liste</h1>

    <div class="button"><a href="{{ route('todo.index') }}" class="btn btn-outline-secondary">Alle Todo Listen</a></div>

    <div id="form" class="form">
        <form action="{{ route('todo.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name"
                    value="{{ old('name') }}">
                @error('name')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-dark">speichern</button>
        </form>
    </div>

@endsection

resources/views/todo/edit.blade.php
@extends('layouts.main')
@section('pageTitle', 'edit ToDo')

@section('content')
    <h1>Todo Liste ändern</h1>
    <div class="button"><a href="{{ route('todo.index') }}" class="btn btn-outline-secondary">Alle Todo-Listen</a></div>

    <div id="form" class="form">

        <form action="{{ route('todo.update', $todo->id) }}" method="POST">
            @method('put')
            @csrf

            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name"
                    value="{{ old('name', $todo->name) }}">
                @error('name')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
            </div>
            <button type="submit" class="btn btn-dark">ändern</button>
        </form>
    </div>
@endsection

resources/views/todo/index.blade.php
@extends('layouts.main')
@section('pageTitle')

@section('content')

    <div class="button"><a href="{{ route('todo.create') }}" class="btn btn-outline-secondary">Neue ToDo Liste</a></div>
    <h1>Todo-Listen</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Erstellungsdatum</th>
                <th scope="col">Todo Items</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>

            {{-- foreach-> DB --}}
            @foreach ($todos as $todo)
                <tr>
                    <th scope="row">{{ $todo->id }}</th>
                    <td>{{ $todo->name }}</td>
                    {{-- Datum formatieren: --}}
                    {{-- AppServiceProvider.php ->  setLocale f Carbon --}}
                    <td>{{ $todo->created_at->formatLocalized('%a, %d.%m.%Y') }}</td>
                    <td>
                        <ul>
                            @foreach ($todo->todoitems as $item)
                                <li>{{ $item->name }}</li>
                            @endforeach
                        </ul>
                    </td>
                    <td><a href="{{ route('todo.show', $todo->id) }}" class="btn btn-outline-dark fa fa-eye"></a></td>
                    <td><a href="{{ route('todo.edit', $todo->id) }}" class="btn btn-outline-dark fa fa-edit"></a></td>
                    <td>
                        @if ($todo->todoitems_count < 1)
                            <form action="{{ route('todo.destroy', $todo->id) }}" method="POST" class="delete"
                                data-title="{{ $todo->name }}"
                                data-body="Soll die Todo- Liste <strong>{{ $todo->name }}</strong> wirklich gelöscht werden?">
                                @method('delete')
                                @csrf
                                {{-- font awesome icon: fa-trash --}}
                                <button type="submit" class="btn btn-outline-danger fa fa-check-circle"></button>
                            </form>
                        @endif
                    </td>
                </tr>
            @endforeach

        </tbody>
    </table>
@endsection

@if (session('success'))
    @section('jsScript')
        myToastr('success','{{ session('success') }}');
    @endsection
@endif

resources/views/todo/show.blade.php
@extends('layouts.main')
@section('pageTitle')

@section('content')

    <div class="button"><a href="{{ route('todo.index') }}" class="btn btn-outline-secondary">Alle Todo-Listen</a></div>

    <h1>{{ $todo->name }}</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>

            @foreach ($todoitems as $item)
                <tr>
                    <th scope="row">{{ $item->id }}</th>
                    <td>{{ $item->name }}</td>
                    <td><a href="{{ route('todoitem.edit', $item->id) }}" class="btn btn-outline-dark fa fa-edit"></a>
                    </td>
                    <td>
                        <form action="{{ route('todoitem.destroy', $item->id) }}" method="post" class="delete"
                            data-title="{{ $item->name }}"
                            data-body=" Soll das Todo- Item <strong>{{ $item->name }}</strong> gelöscht werden?">
                            @method('delete')
                            @csrf
                            <button type="submit" class="btn btn-outline-danger fa fa-check-circle"></button>
                        </form>
                    </td>
                </tr>
            @endforeach

            {{-- <tr>
                <th scope="row">1</th>
                <td>HTML/CSS</td>
                <td><a href="../todoitem/edit.html" class="btn btn-outline-dark fa fa-edit"></a></td>
                <td>
                    <button type="submit" class="btn btn-outline-danger fa fa-trash"></button>
                </td>
            </tr>
            <tr>
                <th scope="row">1</th>
                <td>Backend</td>
                <td><a href="../todoitem/edit.html" class="btn btn-outline-dark fa fa-edit"></a></td>
                <td>
                    <button type="submit" class="btn btn-outline-danger fa fa-trash"></button>
                </td>
            </tr> --}}
        </tbody>
    </table>
    <br>
    <br>
    <h2>Neues Todo Item</h2>

    <div id="form" class="form">
        <form action="{{ route('todoitem.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <label for="name">Todo-Item Name</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name"
                    value="{{ old('name') }}">
                @error('name')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
                {{-- Übermitteln der id des akt. zugehörigen Todos: --}}
                <input type="text" hidden class="form-control" name="todo_id" id="todo_id" value="{{ $todo->id }}">

            </div>
            <button type="submit" class="btn btn-dark">speichern</button>
        </form>
    </div>

@endsection