routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return 'Herzlich Willkommen und ab an die <a href="/todo">Arbeit!</a>';
});
//Todo (Aufgaben/ Projekte)
Route::resource('/todo','TodoController');
//TodoItem (Unteraufgaben)
Route::post('/todoitem','TodoItemController@store')->name('todoitem.store');
Route::get('/todoitem/{todoitem}/edit','TodoItemController@edit')->name('todoitem.edit');
Route::put('/todoitem/{todoitem}','TodoItemController@update')->name('todoitem.update');
Route::delete('/todoitem/{todoitem}','TodoItemController@destroy')->name('todoitem.destroy');

app/Models/TodoItem.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TodoItem extends Model
{
    use HasFactory;

    protected $fillable = [
        'todo_id',
        'name'
    ];
    
    // Def. Tabellenverhältnisse TodoItem : Todo == n : 1
    public function todo(){
        return $this->belongsTo(Todo::class,'id','todo_id');
    }
    
}

app/Http/Controllers/TodoItemController.php
<?php

namespace App\Http\Controllers;

use App\Models\Todo;
use App\Models\TodoItem;
use Illuminate\Http\Request;

class TodoItemController extends Controller
{
    public $rules=[
        'name'=> 'required|min:3|unique:todo_items,name',
        //'todo_id' => 'exists:todos,id'
    ];
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Todo $todo)
    {
        //dd($request->all());
        $request->validate($this->rules);
        //TodoItem::create(['name'=>$request->name, 'todo_id'=>$request? ])
        //$new=
        TodoItem::create($request->all());
        //dd($new);
        return back()->with('success','Neue Unteraufgabe '.$request->name.' erstellt');
    }
/**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Todoitem  $todoitem
     * @return \Illuminate\Http\Response
     */
    public function edit(TodoItem $todoitem)
    {
        return view('todoitem.edit',compact('todoitem'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\TodoItem  $todoitem
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TodoItem $todoitem)
    {
        //Validierung
        $request->validate($this->rules);
        //Updaten
        $todoitem->update(['name' => $request->name]);
        //dd('update item');
        return redirect()->route('todo.show',$request->todo_id)->with('success','Unteraufgabe '.$request->name.' wurde geändert.');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $todoitem=TodoItem::find($id);
        
        if($todoitem){
            $status=200;
            $key= 'success';
            $msg='Unteraufgabe '.$todoitem->name.' wurde erledigt!';
            TodoItem::destroy($id);
        }
        else {
            $status=404;
            $key='error';
            $msg = 'Unteraufgabe nicht gefunden!';
        }
        
        if(request()->ajax() ){
            return response()->json(compact('status','msg'));
        }
        return back()->with($key, $msg);
    }

}

resources/views/todoitem/edit.blade.php
@extends('layouts.main')
@section('pageTitle')

@section('content')

    <h1>Todo Item ändern</h1>
    <div class="button"><a href="{{ route('todo.index') }}" class="btn btn-outline-secondary">Alle DoTo's</a></div>

    <div id="form" class="form">
        <form action="{{ route('todoitem.update', $todoitem->id) }}" method="post">
            @method('put')
            @csrf
            <div class="form-group">
                <label for="title">Name</label>
                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" id="name"
                    value="{{ old('name', $todoitem->name) }}">
                @error('name')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror

                <input type="text" hidden class="form-control" name="id" id="id" value="{{ $todoitem->id }}">
                <input type="text" hidden class="form-control" name="todo_id" id="todo_id"
                    value="{{ $todoitem->todo_id }}">
            </div>
            <button type="submit" class="btn btn-dark">speichern</button>
        </form>
    </div>
@endsection